import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth].js";
import Login from "./components/Login";
import Logout from "./components/Logout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div style={{ zIndex: 99, position: "relative", background: "#fff" }}>
          {session ? (
            <span>
              {session.user?.email}
              <Logout />
            </span>
          ) : (
            <Login />
          )}
        </div>

        {children}
      </body>
    </html>
  );
}
